feat: add --with-external-pcre
I was getting an error that looked like:

```
Fatal error: Uncaught InvalidArgumentException: RegexIterator::__construct(): Allocation of JIT memory failed, PCRE JIT will be disabled. This is likely caused by security restrictions. Either grant PHP permission to allocate executable memory, or set pcre.jit=0 in /Users/username/src/php-from-source/php-7.4.30/ext/phar/phar.php:1133
Stack trace:
  thrown in /Users/username/src/php-from-source/php-7.4.30/ext/phar/phar.php on line 1133
```

As a first attempt, I patched the source with this, which worked, but
didn't seem like the right way to go, hence using `--with-external-pcre`:

```shell
echo patching "$(pwd)/ext/phar/build_precommand.php"
sed -i .bak '3i\
ini_set("pcre.jit", "0");
' ext/phar/build_precommand.php
```